apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: obce4p3u5-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-f7375e1bd5.one4.p3.openshiftapps.com/rhtap/rhtap-qe-go:2f50367ced62a0400f3d991418365edad9b823fd@sha256:8ed01d816253938405283b70ea72f94f5263c6c80057bbe6aced37ae18f9a356
          name: container-image
